### ISSUE TITLE
App is crashing after new update

### ISSUE THREAD

**Issue by NikunjKhangwal** [GustavoASantos/Noti#25]
The app sometimes randomly crash for me in the new update. It's probably when multiple progress are going on but I'm not sure

**Crash Log**

FATAL EXCEPTION: main
Process: com.gustavoas.noti, PID: 13160
java.lang.IllegalArgumentException: Cannot round NaN value.
	at v2.a.n2(SourceFile:1)
	at o2.c.run(SourceFile:47)
	at com.gustavoas.noti.services.NotificationListenerService.g(SourceFile:1)
	at com.gustavoas.noti.services.NotificationListenerService.onNotificationPosted(SourceFile:236)
	at android.service.notification.NotificationListenerService.onNotificationPosted(NotificationListenerService.java:444)
	at android.service.notification.NotificationListenerService$MyHandler.handleMessage(NotificationListenerService.java:2305)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:210)
	at android.os.Looper.loop(Looper.java:299)
	at android.app.ActivityThread.main(ActivityThread.java:8280)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:576)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1073)

**Comment by GustavoASantos** [comment]
Thanks for the log. I'll fix it!
